port: 4223
http_port: 8223
server_name: n1

jetstream {
  store_dir: "./scripts/cluster/data/n1"
}

cluster {
  name: failover_test
  listen: 127.0.0.1:6223
  routes: [
    nats-route://127.0.0.1:6224
    nats-route://127.0.0.1:6225
  ]
}
