port: 4224
http_port: 8224
server_name: n2

jetstream {
  store_dir: "./scripts/cluster/data/n2"
}

cluster {
  name: failover_test
  listen: 127.0.0.1:6224
  routes: [
    nats-route://127.0.0.1:6223
    nats-route://127.0.0.1:6225
  ]
}
