port: 4225
http_port: 8225
server_name: n3

jetstream {
  store_dir: "./scripts/cluster/data/n3"
}

cluster {
  name: failover_test
  listen: 127.0.0.1:6225
  routes: [
    nats-route://127.0.0.1:6223
    nats-route://127.0.0.1:6224
  ]
}
